version: '2'

services:
  runtime:
    volumes:
     - .:/opt/connectors
    image: sitapati/c8-connector-worker-runtime-nodejs:latest
    environment:
      - LOG_LEVEL=INFO
      - ZEEBE_ADDRESS
      - ZEEBE_CLIENT_ID
      - ZEEBE_CLIENT_SECRET
      - ZEEBE_AUTHORIZATION_SERVER_URL
      - REDIS_HOSTNAME
      - REDIS_PORT
      - REDIS_USER
      - REDIS_SECRET